### ISSUE TITLE
Revamp and clean up layout of the community show page

### ISSUE THREAD

**Issue by grimm** [gina-alaska/awrvi#132] opened 2016-03-28 19:13 UTC
A unlogged in guest should see text telling them how to become a full user who can enter index information.

**Comment by teknofire** [comment] 2016-03-29 18:17
This also needs to include view of the latest finalized index item

**Comment by teknofire** [comment] 2016-03-30 20:40
Just realized this is a duplicate of #98

**Closed as completed** 2016-03-30 20:41 UTC
